### PR TITLE
[HDFS exporter] Fix ConcurrentModificationException

### PR DESCRIPTION
**Pull request by gray-matter**
computeIfAbsent already fills the resulting value, no need to put

### CODE REVIEW

**Comment by gray-matter** [comment]
@ashangit: The initial code didn't make sense as it was assigning a value while also returning it and it's not what computeIfAbsent accepts. There's no other unprotected access to this map and this solves the issue on my machine. Not sure precisely why, but this was fishy and seems to do the trick. NB: the important commit is the first one, in case it was not clear when reviewing.

**Comment by jpbempel** [comment]
Can you provide the stacktrace of the ConcurrentModificationException you had?

**Comment by gray-matter** [comment]
`[Thread-5] ERROR com.criteo.hadoop.garmadon.reader.GarmadonReader - unexpected exception while reading
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1139)
	at com.criteo.hadoop.garmadon.hdfs.writer.PartitionedWriter.getWriter(PartitionedWriter.java:243)
	at com.criteo.hadoop.garmadon.hdfs.writer.PartitionedWriter.write(PartitionedWriter.java:76)
	at com.criteo.hadoop.garmadon.hdfs.HdfsExporter.lambda$buildGarmadonMessageHandler$1(HdfsExporter.java:225)
	at com.criteo.hadoop.garmadon.reader.GarmadonReader$Reader.readConsumerRecords(GarmadonReader.java:186)
	at com.criteo.hadoop.garmadon.reader.GarmadonReader$Reader.run(GarmadonReader.java:106)
	at java.base/java.lang.Thread.run(Thread.java:844)
[Thread-5] INFO com.criteo.hadoop.garmadon.reader.GarmadonReader - stopped reading
[Thread-5] INFO com.criteo.hadoop.garmadon.reader.GarmadonReader - received 4 messages
[main] ERROR com.criteo.hadoop.garmadon.hdfs.HdfsExporter - Reader thread interrupted
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2044)
	at com.criteo.hadoop.garmadon.hdfs.HdfsExporter.main(HdfsExporter.java:147)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1139)
	at com.criteo.hadoop.garmadon.hdfs.writer.PartitionedWriter.getWriter(PartitionedWriter.java:243)
	at com.criteo.hadoop.garmadon.hdfs.writer.PartitionedWriter.write(PartitionedWriter.java:76)
	at com.criteo.hadoop.garmadon.hdfs.HdfsExporter.lambda$buildGarmadonMessageHandler$1(HdfsExporter.java:225)
	at com.criteo.hadoop.garmadon.reader.GarmadonReader$Reader.readConsumerRecords(GarmadonReader.java:186)
	at com.criteo.hadoop.garmadon.reader.GarmadonReader$Reader.run(GarmadonReader.java:106)
	at java.base/java.lang.Thread.run(Thread.java:844)`

**Comment by jpbempel** [comment]
ok It's because you recursively modify the map, this is tricky in computeIfAbsent!!

**Pull request merged**
